---
title: "1-3-Skills"
output:
  html_document:
    highlight: null
    mathjax: null
    css: SFRPG.css

---




Skill Check Difficulty table

Easy 8 (65% at +0)
Normal 12 (65% at +4)
Hard 16 (65% at +8) - requires trained
Very Hard 20 (65% at +12) - requires focus

Difficulty guide
- Easy - Anyone can do it, but an untrained character may sometimes fail this or require extra time or help
- Normal - Hard for untrained characters, trained characters will handle it most of the time.
- Hard - Requires training, only the most talented can do it reliably.
- Very Hard - Only achievable by top experts, with effort.
- Impossible - Only achievable by top experts with significant assistance and luck.


Skill | Ability | Summary
-- | -- | -- 
Athletics | Strength | Sprinting, Climbing, Swimming
Authority | Strength | Intimidation, Leadership, Military
Concentration | Constitution | Study, Craftsmanship, Art
Endurance | Constitution | Stamina, Partying, First Aid
Acrobatics | Dexterity | Balance, Jumping, Tumbling
Stealth | Dexterity | Hiding, Secrets, Codes
Perception | Wisdom | Observation, Empathy, Memory
Nature | Wisdom | Flora, Fauna, Environment, Anatomy
Diplomacy | Charisma | Rethoric, Etiquette, Politics
Trickery | Charisma | Deception, Gossip, Sleigh of Hand
Arcana | Intelligence | Magic, Science, Cosmology
Lore | Intelligence | History, Geography, Law


Athletics
Lift or Drag Load
N: Lift Heavy Load
VH: Lift Very Heavy Load
I: Lift Impossible Load
Throw
N: Throw Moderate Load
H: Throw Heavy Load
I: Throw Very Heavy Load
Walk with load
H: Walk with Heavy Load
I: Walk with Very Heavy Load
Climb
E: Climb ladder, or wall with prepared rope 
N: Climb rope
H: Climb wall with handholds
I: Climb smooth wall
-1 with Climbing Gear
- 1 with Moderate Load
- 2 with Heavy Load
Swim
E: Swim In calm water
N: Swim in Running water
H: Swim in Rough water or against current
-1 if just floating
+1 for Heavy Armor
+1 for Heavy Load
+1 if underwater
Sprint
E: Outrun a slower character
N: Outrun a similar speed character
H: Outrun a faster character
+1 if opponent Trained in Athletics
+1 if opponent Focused in Athletics
+1 Moderate Load
+2 Heavy Load
Break
H: Break a regular door
VH: Break a reinforced door, or a rope binding you
I: Break a portcullis,  or a chain or manacle binding you
Misc
N: Row a boat

Authority
Demoralize opponents or raise allies’ morale
H: Demoralize or raise morale
+1 if opponents stronger
- 1 if opponents weaker
+1 if opponents badly damaged
- 1 if allies badly damaged
+1 if opponents Trained in Authority
+1 if opponents Focused in Authority 

Command
N: Command your subordinate
H: Command a lower status character
+2: Unreasonable request

Interrogate
H: Interrogate prisoner
-1: Use violence

Lead
H: Direct team in coordinated task
-1: Trained team
+1: Stressful scenario
Other (TODO)
Strategy/Tactics
Interrogation

Endurance:
M: Defeat a same-size opponent in an eating or drinking contest
+1 per size different if opponent is larger
- 1 per size different if opponent is smaller
+1 if opponent Trained in Endurance
+1 if opponent Focused in Endurance

M: Sprint or similar level of effort for 2 consecutive turns
+1 per consecutive turn after that

M: Run for 10 minutes (or equivalent sustained effort)
H: Run for 1 hour
VH: Run for 4 hours

M: Hold Breath for 2 minutes
+1 per 2 extra minutes
+1 if exerting

M: Take painful maneuver for a turn (e.g. touch flame, walk on glass shards)
H: Take painful maneuver for a minute
VH: Take painful maneuver for 10 minutes

E: Take night watch for 2 hours
+1 per extra 2 hours
+1 if not well rested (e.g. watch in consecutive nights)

M: First Aid
+1 On oneself
+1 Serious Injury

M: In a conversation, resist provocation or other verbal attack from a character untrained in the relevant skill.
H: opponent Trained in relevant skill
VH: opponent Focused in relevant skill

Concentration
E: Study or craft for 10 minutes
M: Study or craft for 2 hours
H study or craft for 8 hours
VH: study or craft for 24 hours
Note: Often use in multi-skill checks

M: In a conversation with an opponent untrained in Trickery, point out a contradiction, or prevent a change of topic, or remain alert after a long digression.
H: opponent Trained in Trickery
VH: opponent Focused in Trickery

M: Perform a complex task while in a stressful situation
+1 in combat

M: Remember a detail observed in the recent past
+1: Minor detail seen or heard without paying attention
+1: Distant past

- M: Navigate through an unfamiliar urban environment while travelling slowly
- -2 Familiar environment
+1: Gain a general understanding of the kinds of people inhabiting the area and how to avoid casual encounters with them.
- +1 Harsh weather or poor visibility
- +1: Travelling at regular speed
- +2 Travelling fast

Note: Urban environments include civilized settlements such as cities or villages, as well as buildings, ruins, dungeons...



Stealth
M: Infiltrate an area watched by sentinels Untrained in Perception, in the dark
+1 If sentinels are Trained in Perception
+1 If sentinels are Focused in Perception
+1 In daylight.

M: Generate a code secure against characters Untrained in Stealth
+1 against characters Trained in Stealth
+1 against characters Focused in Stealth

H: Break a code generated by a character Untrained in Stealth
+1 by a character Trained in Stealth
+1 by a character Focused in Stealth

M: Communicate simple message by signs. Observers Untrained in Perception do not notice this.
+1: Complex message
+1: Observers Trained in Perception do not notice this.
+1: Observers Focused in Perception do not notice this.
Note: This can also be applied to other means of communication

M: Hide characters or objects against searchers Untrained in Perception
+1 Against searchers Trained in Perception
+1 Against searchers Focused in Perception
+1 Hidden in particularly easy to find place
-1 Hidden in particularly difficult to find place

M: In conversation, conceal reaction or feelings about a subject from opponents untrained in Perception
+1 opponent Trained in Perception
+1 opponent Focused in Perception
+1 if particularly taken by surprise by subject of conversation
- 1 if particularly prepared for subject of conversation

Acrobatics
E: While moving slowly, traverse an  obstacle 1 size smaller than you
+1: Obstacle same size as you
+2: Obstacle 1 size larger than you
+1: Moving at normal speed
+2: Running

E: With a running start, jump over a short pit or similar obstacle
+1 long pit
+2 very long pit
+1 No running start
+1 Jump over obstacle, or landing at a higher point.

E: Move slowly over a narrow or slippery surface
+1 Move over a rope or cable
+1 surface is tilted
+1 Move at normal speed
+2 Run
+1 In combat.

M: Land safely and prone from a short fall
+1: fall from medium height
+2: fall from great height
+1: do not become prone

M: In a few hours, break free from soft bindings such as ropes
+1: hard bindings such as manacles or chains
+1: Reduce time to a few minutes
+2: Reduce time to a few seconds
Note: This check is likely to be noticed if watched. Concealing the attempt requires using Stealth in addition to Acrobatics.



Perception
M: Keep watch over an area in the dark, locating any infiltrators Untrained in Stealth
+1 also locate infiltrators Trained in Stealth
+1 also locate infiltrators Focused in Stealth
-1 In daylight

M: Locate nearby characters or objects hidden by characters Untrained in Stealth
+1 also locate if hidden by characters Trained in Stealth
+1 also locate if hidden by characters Focused in Stealth
-1 if Hidden in particularly easy to find place
+1 if Hidden in particularly difficult to find place

M: In conversation, detect reaction or feelings concealed by opponent untrained in Stealth
+1 opponent Trained in Stealth
+1 opponent Focused in Stealth
-1 if particularly taken by surprise by subject of conversation
+ 1 if particularly prepared for subject of conversation

M: See through illusion or disguise performed by an opponent Untrained in Trickery
+ opponent Trained in Trickery
+ opponent Focused in Trickery





Nature

- M: Navigate through an unfamiliar natural environment while travelling slowly
- -2 Familiar environment
+1: Gain a general understanding of the creatures inhabiting the area and how to avoid casual encounters with them.
- +1 Harsh weather or poor visibility
- +1: Travelling at regular speed
- +2 Travelling fast

Note: Natural environments include non-urban locations within the natural plane such as forests, caves, deserts...

- M: Recognize unknown species of natural creature. You gain a basic idea of that species’ behaviour and racial traits.
- +1: You gain a deep understanding of that species’ behaviour and racial traits.
- +1 Rare species
- +1 Species of non-natural creature originated in the Fey plane

Note: Natural creatures include most common animals and plants, as well as humanoids, magical beasts, and oozes. The following are excluded:
Creatures originated in planes other than the natural plane
Creatures created artificially through magical, divine, scientific or other means
Dragons and creatures related to dragons

- H: Diagnose and treat common disease
- +1: Rare disease

- M: Follow tracks while travelling slowly
- -1: Tracks on mud, snow, or similarly easy to follow terrain
- +1: Tracks on river or similarly hard to follow terrain.
- +1: Travelling at regular speed
- +2 Travelling fast
- +1: Poor visibility
- Note: If the pursued character are hiding the tracks, [add your perception vs their stealth]. If they are setting false tracks, [add your perception vs their trickery]

- H: Basic communication with Beast: feelings, nearby objects
- +1 with Plant

TODO: Be aware of types of creatures living in an area.

Diplomacy
M: While speaking in public, get the attention of an audience during a short speech
+1: Long speech
+1: Hostile audience

M: In a discussion, offer more convincing arguments than an opponent Untrained in Diplomacy
+1: Opponent Trained in Diplomacy
+1: Opponent Focused in Diplomacy

H: When dealing with a different culture, correctly understand and follow their protocols and rituals
-1: Have previously studied, observed, or been advised about that culture
+1: No shared language

M: When negotiating a deal with an opponent Untrained in Diplomacy, get a general idea of what the opponent is willing to accept.
+1: Find out what is the most you can get from the opponent.
+1: Opponent Trained in Diplomacy.
+1: Opponent Focused in Diplomacy.

M: Predict, in general terms, how a party will react to a certain event or scenario that affects it directly.
+1: Predict reaction about event or scenario that affects the party indirectly.
- 1: You are particularly familiar with that party.
+1: You have limited knowledge about that party.

Note: When talking about specific areas of knowledge, additional skills may be required for the check.

Trickery
Deception, Gossip, Sleigh of Hand

M: In a conversation with an opponent Untrained in Concentration, conceal a contradiction, or force a change of topic, or distract with a long digression.
+1: opponent Trained in Concentration
+1: opponent Focused in Concentration

M: Fool an opponent Untrained in Trickery with a plausible bluff or lie
+1: opponent Trained in Trickery
+1: opponent Focused in Trickery
-1: opponent wants to believe the lie
+1: bluff or lie is far-fetched, exaggerated, or unlikely
+2: outrageous bluff or lie

M: Gather information about commonly known gossip or rumors
-1: You provide similarly valuable information in exchange, or otherwise offer something of comparable value
+1: little known gossip or rumors
+2: Closely held secrets, sensitive information

M: In presence of opponents untrained in Perception and Trickery, perform an act of sleight of hand, or pick a pocket.
+1: opponent Trained in  Perception or Trickery
+1: opponent Focused in Perception or Trickery

H: Pick a simple lock
+1: Complex lock

Arcana
M: Recognize unknown species of non-natural creature. You gain a basic idea of that species’ behaviour and racial traits.
-1: The creature is related to the character’s background (e.g. their power source, race or plane of origin)
+1: You gain a deep understanding of that species’ behaviour and racial traits.
+1 Rare species

Note: Non-natural creatures include:
Creatures originated in planes other than the natural plane
Creatures created through magical, divine, scientific or other non-conventional means
Dragons and creatures related to dragons

M: After an hour of observation, gain a basic understanding of an object, enchantment, mechanism, etc. created through magical, divine, scientific or other non-conventional means.
+1: A minute of observation
+2: A round of observation
-1: Target is related to the character’s background (e.g. their power source, race, or plane of origin)

M: Navigate through an unfamiliar supernatural environment while travelling slowly
-2 Familiar environment
+1: Gain a general understanding of the creatures inhabiting the area and how to avoid casual encounters with them.
+1 Harsh weather or poor visibility
+1: Travelling at regular speed
+2 Travelling fast

Note: Supernatural environments include exotic environments in foreign planes or created through magical, divine, scientific or other non-conventional means: Levitating islands, enchanted forests, mirror galleries, dream landscapes...


Lore

M: Recall a well known legend, song or piece of history from a familiar culture
+1 Obscure legend, song or piece of history
+1 Foreign culture

M: Understand a non-obvious aspect of law, customs, politics from a familiar culture.
+1: Obscure aspect of law, customs, politics
+1: Foreign culture
+1: Knowledge of these issues in past ages

M: Identify the top members of the nobility, church and similarly important organizations in a familiar culture
+1: Also be aware of members occupying secondary roles, as well as the different factions within the organization and the relationships between them
+1: Foreign culture
+1: In past times
+1: Knowledge of these issues in past ages

M: Recognize origin of unknown humanoids from familiar culture. You gain a basic idea of that culture’s typical behaviour and racial traits.
-1: Your own culture
+1: Foreign culture
+1: You gain a deep understanding of that culture’s typical behaviour and racial traits.
+1 Rare culture

M: Be aware of the main settlements (e.g. larger towns, cities) and landmarks (e.g. main rivers, lakes, mountain ranges, islands…) from a familiar region, and have a general idea of their location.
+1: Also know lesser settlements and landmarks, and have a fairly accurate idea of the distances between them, and of the peoples that inhabit them.
+1: Unfamiliar region

map

humanoid species/culture trait
