---
title: "Chapter B1 - Races"
output: 
  html_document:
    highlight: null
    mathjax: null
    css: SFRPG.css

---

TODO: FIX FOLDERS

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
basedir <- dirname(getwd())
cat(basedir)
source(file.path(basedir,"scripts","1-01-Race-csv-to-html.R"))
raceList <- getRaceList(basedir)

printRaceFeatures <- function (race)
{
  cat(race$stats.htm)
  cat('<h4>Race Features</h4>')
  cat(race$feature.df$features.htm)
}

printRacePowers <- function (race)
{
    cat(race$powers.htm)
}

```



## Human{.newPage}
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
currentRace <- raceList$Human$Human
printRaceFeatures(currentRace)
```
#### Race Powers
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
printRacePowers(currentRace)
```

## Orc{.newPage}
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
currentRace <- raceList$Orc$Orc
printRaceFeatures(currentRace)
```
#### Race Powers
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
printRacePowers(currentRace)
```

## Orc{.newPage}
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
currentRace <- raceList$Orc$Orc
printRaceFeatures(currentRace)
```
#### Race Powers
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
printRacePowers(currentRace)
```
