# Adventuring

As players characters go on adventures, they will face a series of challenges 
that test them and drain their resources. 
There are two main types of encounters in the game:

- **Skill encounter**s:  The PCs interact with the environment and other 
  characters to solve a problem. This is primarily handled by the Skill system.
- **Combat encounters**: The PCs fight monsters for survival or to achieve a
  goal. This is primarily handled by the Combat system.

In addition, it is possible to have mixed encounters where both character 
Skills and Combat abilities are in the spotlight.
We call these mixed encounters. Note that characters still get to use their 
Skills in regular Combat encounters if they choose to - the difference 
in mixed encounters is that there are explicit goals that require the use of 
Skills.

A typical encounter has the following consequences:

- **Resource use**: Characters have a stat called **Stamina** that determines 
how many encounters they can take before stopping to take a Long Rest. Stamina 
can be lost in an encounter by receiving wounds, failing Skill Checks or using 
certain special powers. In addition,taking a Short Rest to recover after an 
encounter also spends 1 Stamina point.
- **Rewards**: Characters can gain experience points, gold, and treasure
 after an encounter.
- **Campaign consequences**: Depending on the degree of success of an encounter,
 there can be consequences for the Player Characters, their allies, or the
 environment.

In addition, a particularly disastrous encounter can have Player Characters
 end up permanently crippled or even dead.

## Resource management

Player characters have two types of resources: per-encounter resources that are
 usually replenished after each challenge, and campaign resources that are 
 recovered at a slower pace.

Encounter resources are:

- **Hit Points.** How much damage the character can take before
  falling unconscious.
- **Vitality.** A stat that is spent to use healing powers, and is lost
  when knocked unconscious.
- **Morale.** How much the character can use skills this encounter. Characters
  lose Morale whenever they fail a Skill Check.
- **Encounter powers.** Strong powers that, once spent, are recovered with a
  Short Rest.


Campaign resources are:

- **Stamina**. A measure of how many more encounters the character can have 
  this day. Stamina is used to take Short Rests, and may be lost when out of
  encounter resources.
- **Daily powers**. Very strong powers that, once spent, are only recovered on
  a Full Rest or, occasionally, after achieving a milestone.
- **Action Points**. Points that can be spent to gain extra actions in an 
  encounter. Gained after each milestone. 
  
Other player stats that are related to encounter and campaign resources are:

- **Healing Surge**: How many Hit Points the character recovers  when healing. 
  Many powers refer to using a Healing Surge - this means spending
  1 Vitality to recover HP equal to their Healing Surge value. In addition, 
  whenever a character below 1 HP is healed back above 0 HP, if this would leave
  them at a HP value lower than their Healing Surge, their HP becomes equal 
  to their Healing Surge value instead.
- **Exhaustion**: A stat tracking a negative condition related to running out
  of Stamina. Characters gain -1 to attack rolls and skill checks for each point
  of Exhaustion. Exhaustion is gained by losing Stamina while at 0 Stamina, 
  and is removed by recovering Stamina. At the GM's discretion, a character with 
  5 or more Exhaustion may become incapacitated until rested. 


The different types of resources are inter-related. Generally speaking,
taking wounds or skill failures while out of encounter resources will result in
loss of Stamina. These are the consequences for running out of each type of 
resource:

- **Hit Points**. A character reduced below 1 HP falls Unconscious until healed
  back to 1 or more HP, and is Bleeding until healed for any amount. The first
  time a PC drops  to 0 HP in an 
  encounter, they lose 1 Vitality. In addition, a Bleeding character must make
  a Vitality Saving Throw at the end of each of their turns: on a failure, 
  they lose 1 Vitality. If the save is successful, they can take  
  a Saving Throw to become stabilised and stop being Bleeding. If a
  stabilised character below 1 HP takes damage, they become Bleeding again.
- **Vitality**. A character reduced to 0 Vitality loses 1 Stamina whenever they
  would lose or spend a Vitality point.
- **Morale**. A character reduced to 0 Morale must make a Morale Saving Throw
  whenever they would lose or spend a Morale point: on a failure, they lose 1
  Stamina. In addition, characters with 0 Morale gain a -2 penalty to 
  Skill Checks.
- **Stamina and Exhaustion**. A character reduced to 0 Stamina gains 1 
  Exhaustion whenever they would lose or spend a Stamina point. A character
  with Exhaustion that recovers Stamina loses 1 Exhaustion for each point of
  Stamina recovered.

Note that characters suffer no negative consequences for running out of 
Encounter Powers, Daily Powers or Action Points. Players should try to use
these resources carefully to avoid running out of HP and make their Stamina
last as long as possible.

**Sidebar: Stat Values**
A typical character has Stamina 6, Vitality 1, and Morale 2.
Stamina, Vitality and Morale are based on a character’s class.
Healing Surge Value is equal to a quarter of a character’s base Hit Points, 
plus their Constitution / Charisma modifier.

## Resting

Player Characters can rest to recover resources. There are three types of rest, 
depending on the time and conditions of resting. In addition, some resources
can also be recovered upon completing campaign objectives:

- **Short Rest**. A quick stop to catch a breath after a challenge. 
  A character spends a Stamina point to regain all Encounter resources.
- **Long Rest**. Camping to sleep for the night during an adventure.
 The character regains all Encounter resources and a Stamina point. 
- **Full Rest**. Proper rest at a safe location after completing a major 
  objective. The character regains all Encounter and Campaign resources.
- **Milestone**. Morale boost after completing a partial objective 
  (e.g. 2 challenges). The character gains an Action point and gets a chance to
   recover Daily Powers.
   
Short Rests are available whenever characters are not in immediate danger. 
Long Rests require characters to find a relatively safe location where they 
can camp for at least 8 hours. Usually, characters won't be able to take more
than one Long Rest every 24 hours. Full Rests have the same requirements as 
Long Rests, plus they can only be taken at specific points during a campaign, 
at the GM's discretion. Usually, characters will only be able to take a Full 
Rest after completing around 6 encounters. Milestones are usually achieved
after completing 2 regular encounters, though at the GM's discretion some 
encounters may count as multiple regular encounters or a fraction of an 
encounter, depending on their difficulty.

After each milestone, Daily Powers can be recovered as follows:
- For each spent Daily Power, the character rolls a D6: On a 6+, the power is
  recovered.
- If the character has no spent Daily Powers and are below their maximum 
  Stamina, they may instead roll a D6: On a 6+, they recover 1 Stamina. 

## Resources and Resting Summary

The following table summarizes how resources are spent and recovered:

- Hit Points:
  - Recover all HP when taking a Short Rest, Long Rest or Full Rest.
  - Recover HP equal to your Healing Surge value whenever you use a Healing
   Surge.
  - Whenever you take damage, lose that many HP.
  - You are Unconscious while below 1 HP.
  - When knocked below 1 HP, you are Bleeding until stabilised.
  - While Bleeding, if you pass a Vitality Saving Throw, you can make a Saving
    Throw to stabilize and stop being Bleeding.
  - When you take damage while below 1 HP and stabilised, you become Bleeding.
  - When healing from below 1 HP to an amount between 1 HP and your Healing
    Surge value, your HP becomes your Healing Surge value instead.
- Vitality: 
  - Recover all Vitality when taking a Short Rest, Long Rest or Full Rest.
  - Lose 1 Vitality when dropping below 1 HP for the first time in an encounter.
  - Lose 1 Vitality when failing a Vitality Saving Throw. You make a Vitality
    Saving Throw at the end of your turn while Bleeding.
  - Lose 1 Vitality when you use a healing surge.
  - If at any point a character would spend or lose Vitality but has no Vitality
   left, they lose 1 Stamina instead. 
- Morale:
  - Recover all Morale when taking a Short Rest, Long Rest or Full Rest.
  - Characters with 0 Morale gain a -2 penalty to 
    Skill Checks
  - Lose 1 Morale when failing a Skill Check.  
  - Spend 1 or more Morale when performing a Ritual.
  - Some types of Skill Check have an additional Morale cost. 
    See skill description for more details.
  - If at any point a character would spend or lose Morale but has no Morale 
    left, they take a Morale Saving Throw for each point of Morale lost.
    For each failure, they lose 1 Stamina.
- Stamina:
  - Spend 1 Stamina to take a Short Rest
  - Lose 1 Stamina when losing 1 Vitality while out of Vitality
  - Lose 1 Stamina failing a Morale Saving Throw.
  - Recover 1 Stamina when taking a Long Rest.
  - Recover all Stamina when taking a Full Rest.
- Exhaustion:
  - Gain 1 Exhaustion when losing 1 Stamina while out of Stamina.
  - Lose 1 Exhaustion for each point of Stamina you recover.

## Dying

The rules for when a character should die are left intentionally vague: this 
is something that should happen on exceptional circumstances with the GM's 
approval. A character may die in the following scenarios:

- Receiving massive damage, e.g. drop to negative HP equal or greater than their
maximum HP.
- All PCs dropping unconscious in a dangerous situation.

The GM should decide on the level of lethality they want for their campaign, 
and communicate this clearly to the players. That said, GMs should be aware that
players can be punished for defeat in ways that do not require death of a PC:

- Instead of dying, a character may receive a permanent wound, such as a -1
  penalty to Stamina, Movement, Fortitude, Reflex, Will or to an Ability Skill 
  bonus. Alternately, a valuable Magic Item may be permanently destroyed
  instead.
- When the entire party drops unconscious in combat, they may be taken prisoner,
  or suffer permanent wounds as described above. Or some PCs may die 
  while others survive.
  
In a campaign with magical healing, it may be possible to recover from permanent
wounds, or even death - see the Ritual chapter for optional rules on this. At 
any rate, such healing should never be too easy, and there should always be a 
significant cost involved.
