# Reference Tables

## Reference - Skills

**Skill Summary**

Skill | Ability | Summary
-- | -- | --- 
Athletics | Strength | Sprinting, Climbing, Swimming
Authority | Strength | Intimidation, Leadership, Military
Concentration | Constitution | Study, Craftsmanship, Art
Endurance | Constitution | Stamina, Wakefulness, Survival
Finesse | Dexterity | Balance, Tumbling, Lockpicking
Stealth | Dexterity | Hiding, Secrets, Ciphers
Perception | Wisdom | Observation, Empathy, Memory
Nature | Wisdom | Flora, Fauna, Environment, Healing
Diplomacy | Charisma | Rethoric, Etiquette, Politics
Trickery | Charisma | Lying, Gossip, Forgery
Arcana | Intelligence | Magic, Science, Cosmology
Lore | Intelligence | History, Geography, Law

**Skill Check Difficulty table**

Abreviation | Check level | DC | Req. Level | Morale cost
-- | -- | -- | -- | --
R | Routine | - |   |  
E | Easy | 8 |   | 1 on Failure
M | Medium | 13 |   | 1 on Failure
H | Hard | 18 |   | 1 on Failure
VH | Very Hard | 23 | Trained | 1 on Failure
I | Legendary | 28 | Master | 2 on Failure
I | Impossible | 33 | Grandmaster | 2 on Failure

**Skill Check Modifiers**

Description | Modifier
--- | --
Character previously failed same check | +1 DC
Allies previously failed same check twice | +1 DC
Advantage | +2
Demoralized | -2

**Roleplaying modifiers**

Modifier | Value
-- | --
Out of character | Failure
Conflicting for character | -2
Matches character | +0
Add character insight | +2

**Skill Actions**

Check | Action | Check | Success | Augment
--- | -- | ---- | ---- |
Simple Skill Check | Standard | Base DC | +1 Progress | +1 DC, +1 Progress |
Partial Skill Check | Standard | Base DC -1 | +1 Progress per 3 successes |
Double Skill Check | 2 Standard | Base DC -1, min of 2 Skills | +1 Progress |
Assist | Standard | Base DC -1, not same skill as assisted check | A character gains Advantage on next check |
Recovery | Standard | Base DC -1, not same skill as recovered check | After failed check, recover 1 Morale or ignore fail penalty. | +1 DC, Minor Action |
Gain Time | Standard | Base DC -1 | Prevent next Escalation Die increase |
Gather Information | Standard | Base DC -2 | Gain clues, find options | +1 DC, Minor Action |
Fail Forward | Challenge ends | Party spends 1 Surge to take Short Rest | Find alternate path  |

**Skill Challenges**

Level | Challenge Tier | Required progress | DC
- | -- | - | -- |
1 | Basic | 3 | Medium
3 | Basic, Long | 5 | Medium
6 | Heroic | 3 | Medium
11 | Heroic, Long | 5 | Hard
16 | Paragon | 3 | Very Hard
21 | Paragon, Long | 5 | Very Hard
26 | Epic | 3 | Legendary
31 | Epic, Long | 5 | Legendary
36 | Impossible | 3 | Impossible

**Roleplaying die roll**

Score | Result
-- | --
Terrible | Failure
Below Average | 1d4+6
Good | 1d4+11
Excellent | 1d4+16

## Reference - Combat {.newPage}

TODO
