# Races

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
basedir <- here::here()
#basedir <- file.path(basedir, 'SFRPG-web')
source(file.path(basedir,"R","1-01-Race-csv-to-html.R"))
raceList <- getRaceList(basedir)

printRaceTitle <- function (raceName, subrace, skipClass=TRUE)
{
  cat("<w:p><w:r><w:br w:type=\"page\"/></w:r></w:p>")
  cat("<p><!-- pagebreak --></p>")
  if(!skipClass)
    {cat(paste('<h2>', raceName,'</h2>',sep=""))}
  cat(paste('<h3>Race: ', subrace,'</h3>',sep=""))
}

printRace <- function (race)
{
  
  cat(race$stats.htm)
  cat('<h4>Race Features</h4>')
  cat(race$features.htm)
  cat("<w:p><w:r><w:br w:type=\"page\"/></w:r></w:p>")
  cat("<p><!-- pagebreak --></p>")
  if (!is.null(race$powers.htm))
  {
    cat('<h4>Race Powers</h4>')
    cat(race$powers.htm)  
  }

}

```

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE, prompt=FALSE}
printRaceTitle('Human', 'Human')
printRace(raceList$Human$Human)
printRaceTitle('Elf', 'Elf')
printRace(raceList$Elf$Elf)
printRaceTitle('Elf', 'High Elf')
printRace(raceList$Elf$`High Elf`)
printRaceTitle('Dwarf', 'Dwarf')
printRace(raceList$Dwarf$Dwarf)
printRaceTitle('Halfling', 'Halfling')
printRace(raceList$Halfling$Halfling)
printRaceTitle('Dragonfolk', 'Dragonfolk')
printRace(raceList$Dragonfolk$Dragonfolk)
printRaceTitle('Orc', 'Orc')
printRace(raceList$Orc$Orc)
```
